export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: "Complex Hotelier Armenopolis",
  description: "Complex Hotelier Armenopolis Gherla",
  keywords: [
    "complex hotelier",
    "Armenopolis",
    "cazare Gherla",
    "hotel baroc Transilvania",
    "hotel istoric România",
    "team building Gherla",
    "facilități premium hotel",
    "sacroterapie România",
    "cazare echipe corporate",
    "locație team building Transilvania",
    "evenimente corporate România",
    "hotel Armenopolis",
    "hotel Karol Gherla",
    "Casa Regina Maria Gherla",
    "hoteluri armenești Transilvania",
    "catedrala armeano-catolică Gherla",
    "Biserica Solomon",
    "Lacul Știucilor",
    "Stufărișul de la Sic",
    "obiective turistice Gherla",
    "patrimoniu cultural Gherla",
    "drumeții Transilvania",
    "jocuri indoor-outdoor",
    "concursuri de gătit",
    "activități corporate",
    "relaxare spa jacuzzi",
    "evenimente în cramă",
    "sporturi de echipă Gherla",
    "plimbări cu caleasca",
    "team building sacroterapie",
    "echipe corporate",
    "evenimente private",
    "retreat-uri corporate",
    "locație business România",
    "cazare echipe mari",
    "activități pentru echipe",
    "cazare în hoteluri istorice din România",
    "locație pentru team building în Transilvania",
    "experiențe personalizate pentru echipe corporate",
    "relaxare și aventură în Gherla",
    "activități de team building lângă Cluj-Napoca",
  ],
  navItems: [
    {
      label: "Acasă",
      href: "/",
    },
    {
      label: "Despre noi",
      href: "/despre-noi",
    },
    {
      label: "Servicii",
      href: "/facilitati",
    },
    {
      label: "Galerie",
      href: "/galerie",
    },
    {
      label: "Obiective turistice",
      href: "/obiective-turistice",
    },
  ],
  navMenuItems: [
    {
      label: "Acasă",
      href: "/",
    },
    {
      label: "Despre noi",
      href: "/despre-noi",
    },
    {
      label: "Servicii",
      href: "/facilitati",
    },
    {
      label: "Galerie",
      href: "/galerie",
    },
    {
      label: "Obiective turistice",
      href: "/obiective-turistice",
    },
  ],
  links: {
    whatsapp: "https://wa.me/40723946272",
    email: "mailto:gherlaccdp@yahoo.com",
  },
};
